<a href="https://colab.research.google.com/github/fundaylncii/PythonQuiz/blob/main/CaseStudy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)
pd.set_option("display.width",1000)

In [ ]:
## import dataset
df = sns.load_dataset("car_crashes")

In [ ]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous', 'ins_premium', 'ins_losses', 'abbrev'], dtype='object')

In [ ]:
## Adding the term NUM to the beginning of numerical values with list comp.
["NUM_" + col.upper() if df[col].dtype != "O" else col.upper()  for col in df.columns]

['NUM_TOTAL',
 'NUM_SPEEDING',
 'NUM_ALCOHOL',
 'NUM_NOT_DISTRACTED',
 'NUM_NO_PREVIOUS',
 'NUM_INS_PREMIUM',
 'NUM_INS_LOSSES',
 'ABBREV']

In [ ]:
## Addin the term FLAG to values without "NO" wit list comp.
[col.upper() + "_FLAG" if "no" not in col.upper() else col for col in df.columns]

['TOTAL_FLAG',
 'SPEEDING_FLAG',
 'ALCOHOL_FLAG',
 'NOT_DISTRACTED_FLAG',
 'NO_PREVIOUS_FLAG',
 'INS_PREMIUM_FLAG',
 'INS_LOSSES_FLAG',
 'ABBREV_FLAG']

In [ ]:
## Create a new df containing different values ​​from the following variable names
od_list = ["abbrev", "no_previous"]
new_cols = [col for col in df.columns if col not in od_list]
df_new = df[new_cols]
df_new.head()

   total  speeding  alcohol  not_distracted  ins_premium  ins_losses
0   18.8     7.332    5.640          18.048       784.55      145.08
1   18.1     7.421    4.525          16.290      1053.48      133.93
2   18.6     6.510    5.208          15.624       899.47      110.35
3   22.4     4.032    5.824          21.056       827.34      142.39
4   12.0     4.200    3.360          10.920       878.41      165.63

In [2]:
dfp = sns.load_dataset("titanic")
dfp.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
## number of male and female passenger
dfp["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
## uniq number of for each columns
dfp.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
## uniq number of "pclass" value
dfp["pclass"].nunique()

3

In [5]:
## what type the "embark" values and changed type
dfp["embarked"].dtype
dfp["embarked"] = dfp["embarked"].astype("category")
dfp["embarked"].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=object)

In [8]:
## All information of those with embarked value c
dfp[dfp["embarked"] == "C"].head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True

In [13]:
## information for passenger who are under 30 age and female

dfp[(dfp["age"] < 30) & (dfp["sex"] == "female")].head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False

In [14]:
## delete the who value from the dataframe
dfp.drop("who", axis=1, inplace=True)
dfp.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,False,NaN,Cherbourg,yes,False

In [20]:
## most repeated values in deck variable
dfp["deck"].mode()[0]

'C'

In [21]:
## count the null values in deck variable
dfp["deck"].isnull().sum()

688

In [ ]:
## replacing null values in deck with the most repeated

In [22]:
dfp["deck"].fillna(dfp["deck"].mode()[0], inplace=True)

In [23]:
## again count the null values in deck variable
dfp["deck"].isnull().sum()

0

In [25]:
## sum count mean values of survived variable in pclass and sex breakdown

dfp.groupby(["pclass","sex"]).agg({"survived":["sum","count","mean"]})

              survived
                   sum count      mean
pclass sex
1      female       91    94  0.968085
       male         45   122  0.368852
2      female       70    76  0.921053
       male         17   108  0.157407
3      female       72   144  0.500000
       male         47   347  0.135447

In [26]:
dfl = sns.load_dataset("tips")
dfl.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
## Find the sum, min , max and average of total bill and tips values of lunch time and female customers accordig to day
dfl[(dfl["time"] == "Lunch") & (dfl["sex"] == "Female")].groupby("day").agg({"total_bill": ["sum","min","max","mean"],
                                                                          "tip":["sum","min","max","mean"]})

<ipython-input-32-a74610ccb282>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfl[(dfl["time"] == "Lunch") & (dfl["sex"] == "Female")].groupby("day").agg({"total_bill": ["sum","min","max","mean"],

     total_bill                            tip
            sum    min    max      mean    sum   min   max      mean
day
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000
Sat        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN
Sun        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN